### ISSUE TITLE
Build the script with pyinstaller

### ISSUE THREAD

**Issue by oskros** [mrpara/d2_plugy_stash_organizer#4]
Consider using pyinstaller to build the script into an exe, so users without python installed can make use of it as well?

**Comment by mrpara** [comment]
I've never used pyinstaller but I'll look into it

**Comment by oskros** [comment]
I used pyinstaller for my MF run counter to compile it, perhaps you can find some inspiration here:
https://github.com/oskros/MF_run_counter/tree/master/build_exe

its relatively easy to use honestly. just pip install pyinstaller and then you could do sth like below. At first run, it creates a ".spec" file, which you can point to afterwards if you want to make edits to the settings for the compiler
pyinstaller "\<path to main.py\>" --windowed --onefile --clean

**Comment by mrpara** [comment]
Added executable release
Thanks for the tip
