### ISSUE TITLE
IndexError parsing stash file

### ISSUE THREAD

**Issue by jkrentz** [mrpara/d2_plugy_stash_organizer#6]
Running main.py directly. Works for my personal stash but is breaking on my shared stash. PlugY 11.02

[sharedstash.zip](https://github.com/mrpara/d2_plugy_stash_organizer/files/5557576/sharedstash.zip)

```
Traceback (most recent call last):
  File ".\main.py", line 351, in <module>
    main()
  File ".\main.py", line 338, in main
    pages_to_ignore, item_list = parse_stash_data(stash_data, config)
  File ".\main.py", line 110, in parse_stash_data
    page_items = get_items(page, ptr)  # Get items in page
  File ".\main.py", line 83, in get_items
    items = chunks_unify_sockets(chunks)
  File ".\main.py", line 72, in chunks_unify_sockets
    item_candidate += chunks.pop(0)
IndexError: pop from empty list
```

**Comment by mrpara** [comment]
Hey, sorry for the late response.
Looking into it.

**Comment by mrpara** [comment]
I've tracked down the problem to a specific item in page 30 of your shared stash, specifically Milabrega's Diadem set crown.
Its item data is screwed up. For some reason it contains the data for 2 items, with the data of the 2nd item being nonsensical. Before I dive in deeper to debug this, please answer me: is it possible that this item was edited by you in some way (for example, removing its sockets via Hero Editor or something along those lines)?

**Comment by mrpara** [comment]
I have also farmed a new Milabrega's Diadem in my own game, ran the tool and it has no problems with it.

**Comment by jkrentz** [comment]
No, I've never used hero editor. If there's some sort or corruption I can try tossing the item and see if this happens again with a new drop. Especially since it looks fine for you.

I'll close. Thanks for looking.
