### ISSUE TITLE
not compatible with PlugY Vesion 10.00

### ISSUE THREAD

**Issue by alian-win** [mrpara/d2_plugy_stash_organizer#7]
# enviorment
D2 Version 1.13c
PlugY Vesion 10.00
# what appened
can't organize JEW items.leave the first page unchanged and lose unique JEWs
here is the d2x file
[JEW.zip](https://github.com/mrpara/d2_plugy_stash_organizer/files/5586390/JEW.zip)

**Comment by mrpara** [comment]
Hi, did you try the solution suggested in the readme?
I'm afraid I can't do anything beyond that. This tool was not designed to be compatible with PlugY 10.00, nor tested with it. I do not even have a plugy 10.00 install. If you manage to solve the issue yourself then please make a PR and I'll be happy to incorporate the bug fixes, but I do not intend to maintain compatibility with versions of PlugY other than 11.02, so long as 11.02 remains the most widely used version with the most support for other projects.

**Comment by mrpara** [comment]
Closing this since no one has offered a solution and I do not intend to support Plugy 10.00 myself
