### ISSUE TITLE
Bad inventory data

### ISSUE THREAD

**Issue by nemosbg** [mrpara/d2_plugy_stash_organizer#8]
Hello. It is amazing that you managed to create such a tool! I hope to get it to work and continue playing the game. I assume I am getting the bad inventory error, because of item code that is wrong/non-existent. Sadly, I do not know how to provide you with an error code, therefore, I am leaving a link to my shared stash file in its normal state before me attempting to sort it. Here it is - [https://www.mediafire.com/file/zyoy1t7l8d61c2q/_LOD_SharedStashSave.sss/file](url) I am immensely hooked again to this game and I will highly appreciate your help. Thanks in advance!

**Comment by nemosbg** [comment]
I did some manual testing and figured the problematic item is the quest's Mephisto's soulstone. I am not sure to which character it belongs, but for now I will just put it in ignored stash tab. I hope this will be helpful to someone.

**Comment by mrpara** [comment]
Thanks for reporting this issue, I'll look into it as soon as I am able to.

**Comment by mrpara** [comment]
Tracked this down to a bug in the num_filled_sockets method in the Item class, which could erroneously return a nonzero number when input was a "simple" item (potions, soulstones, gems, etc). Added an explicit check for simple items. Confirmed that this fixes the issue on the stash file provided.
Closing this now, thanks again for reporting this.
